"""Compile every scene to JSON.

    python resume/build.py     (or:  python -m resume.build)

Writes, for each resume/scenes/<job>.py that exports `scene`:
    src/resume/data/<id>.json      the compiled scene
    src/resume/data/index.json     a list of {id, title, role, period}
    src/resume/data/scenes.generated.ts   a typed binding the Worker imports
"""

from __future__ import annotations

import importlib
import json
import pathlib
import pkgutil
import sys

# Allow `python resume/build.py` (adds the project root to the path so
# `import resume.*` resolves regardless of how the script is invoked).
ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from resume import scenes as scenes_pkg  # noqa: E402
from resume.scene import Scene  # noqa: E402

DATA_DIR = ROOT / "src" / "resume" / "data"


def load_scenes() -> list[Scene]:
    found: list[Scene] = []
    for mod in pkgutil.iter_modules(scenes_pkg.__path__):
        module = importlib.import_module(f"resume.scenes.{mod.name}")
        scene = getattr(module, "scene", None)
        if isinstance(scene, Scene):
            found.append(scene)
    found.sort(key=lambda s: s.id)
    return found


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    scenes = load_scenes()

    index = []
    for s in scenes:
        s.validate()
        path = DATA_DIR / f"{s.id}.json"
        path.write_text(json.dumps(s.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8")
        index.append({"id": s.id, "title": s.title, "role": s.role, "period": s.period})

    (DATA_DIR / "index.json").write_text(
        json.dumps(index, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    # Typed binding: the Worker bundler can't glob JSON, so emit static imports.
    ids = [s.id for s in scenes]
    lines = ["// AUTO-GENERATED by resume/build.py — do not edit by hand.", ""]
    for i in ids:
        lines.append(f'import {i} from "./{i}.json";')
    lines.append("")
    lines.append(f"export const SCENES = [{', '.join(ids)}];")
    lines.append("")
    (DATA_DIR / "scenes.generated.ts").write_text("\n".join(lines), encoding="utf-8")

    print(f"built {len(scenes)} scene(s): {', '.join(ids) or '(none)'}")


if __name__ == "__main__":
    main()
