// AUTO-GENERATED by resume/build.py — do not edit by hand.

import pompeii from "./pompeii.json";
import making_science from "./making_science.json";
import accenture from "./accenture.json";

export const SCENES = [pompeii, making_science, accenture];
